# Generated by Django 5.2.1 on 2025-06-02 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_autor_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='descricao',
            new_name='categoria_descricao',
        ),
        migrations.RenameField(
            model_name='editora',
            old_name='nome',
            new_name='editora_nome',
        ),
    ]
