# Generated by Django 5.2.1 on 2025-06-02 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_rename_descricao_categoria_categoria_descricao_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='categoria_descricao',
            new_name='descricao',
        ),
        migrations.RenameField(
            model_name='editora',
            old_name='editora_nome',
            new_name='nome',
        ),
    ]
